### ISSUE TITLE
菜鸡一枚

### ISSUE THREAD

**Issue by 1161002090** [zhuxiao220/Shop#2]
*.*大佬有没有文档之类的

**Comment by hellozxx** [comment]
没有哦，这还是很多年前我的毕设

**Comment by hellozxx** [comment]
> *.*大佬有没有文档之类的

没有哦，这还是很多年前我的毕设

**Comment by 1161002090** [comment]
好的，没想到会回我



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月15日(星期天) 下午5:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hellozxx/Shop] 菜鸡一枚 (Issue #2)





  
*.*大佬有没有文档之类的
  
没有哦，这还是很多年前我的毕设

**Comment by 1161002090** [comment]
学长，你还记得你的毕业论文叫什么吗，我去知网搜搜




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月15日(星期天) 下午5:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hellozxx/Shop] 菜鸡一枚 (Issue #2)





  
*.*大佬有没有文档之类的
  
没有哦，这还是很多年前我的毕设

**Comment by hellozxx** [comment]
> 学长，你还记得你的毕业论文叫什么吗，我去知网搜搜
> […](#)

《iOS移动端商城的设计与实现》
我在知网搜了一下，没找到。。。。

**Comment by 1161002090** [comment]
。好像就是搜不到，本科生的存库里但不让搜。我没做出来程序，参照你的程序改的，在写论文，所以想问问，有什么文档之类的，打扰了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hellozxx/Shop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月15日(星期天) 晚上8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hellozxx/Shop] 菜鸡一枚 (Issue #2)





  
学长，你还记得你的毕业论文叫什么吗，我去知网搜搜
 …
  
《iOS移动端商城的设计与实现》
 我在知网搜了一下，没找到。。。。
